name: ðŸž PowerShell module bug report
description: Report errors or unexpected behaviors for the Microsoft.PowerPlatform.EnterprisePolicies module.
labels: [needs-triage, bug]

body:
- type: markdown
  attributes:
    value: >
      Thanks for reporting.

      - Make sure you are able to reproduce this issue on the latest released version of [Microsoft.PowerPlatform.EnterprisePolicies](https://www.powershellgallery.com/packages/Microsoft.PowerPlatform.EnterprisePolicies)
      
      - Please search the existing issues to see if there has been a similar issue filed
- type: textarea
  attributes:
    label: Description
    description: >
      Please describe the issue and the expected result here. Paste your repro script and any error/debug output in the next section ("Issue script & Debug output").
  validations:
    required: true
- type: textarea
  attributes:
    label: Issue script & Debug output
    description: >
      Set `$VerbosePreference='Continue'` before running the repro and paste the resulting debug stream in the below textarea

      **âš  ATTENTION:** Be sure to remove any sensitive information that may be in the logs
    render: PowerShell
    placeholder: |
      PS> $VerbosePreference='Continue'
      PS> # The command you ran
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment data
    description: >
      Please run `$PSVersionTable` and paste the output in the below textarea.
    render: PowerShell
    placeholder: |
      PS> $PSVersionTable
  validations:
    required: true
- type: textarea
  attributes:
    label: Module versions
    description: >
      Please run `Get-Module` after cmdlet execution and paste the output in the below textarea.

      If module cannot be installed or imported, please run `Get-Module -ListAvailable` and paste the output.
    render: PowerShell
    placeholder: |
      PS> Get-Module
  validations:
    required: true