trigger:
  branches:
    include:
    - main

pr: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    sdl:
      tsa:
        enabled: true
      binskim:
        enabled: false # Not applicable for this repo
      codeql:
        enabled: true
        compiled:
          enabled: false #No compiled languages in this repo
        runSourceLanguagesInSourceAnalysis: true
      credscan:
        enabled: true
        suppressionsFile: $(Build.SourcesDirectory)/.config/CredScanSuppressions.json
      policheck:
        enabled: true
        exclusionFile: $(Build.SourcesDirectory)/.config/PolicyCheckExclusions.json
      psscriptanalyzer:
        enabled: true
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-2022
        os: windows

    stages:
    - stage: Build
      jobs:
      - job: Build_And_Release
        displayName: "Build and Release"
        steps:
          - template: .pipelines/templates/BuildCommon.yml@self
            parameters:
              Official: true

