trigger:
  branches:
    include:
    - main

pr: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: self
    type: githubenterprise
    name: microsoft/PowerPlatform-EnterprisePolicies

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    sdl:
      tsa:
        enabled: true
      binskim:
        enabled: true
      codeql:
        enabled: true
        compiled:
          enabled: false #No compiled languages in this repo
        runSourceLanguagesInSourceAnalysis: true
      credscan:
        enabled: true
        suppressionsFile: $(Build.SourcesDirectory)/.config/CredScanSuppressions.json
      policheck:
        enabled: true
        exclusionFile: $(Build.SourcesDirectory)/.config/PolicyCheckExclusions.json
      psscriptanalyzer:
        enabled: true
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-2022
        os: windows

    stages:
    - stage: BuildAndRelease
      displayName: "Build and Release"
      jobs:
      - job: Build
        displayName: "Build"
        templateContext:
          outputs:
          - output: pipelineArtifact
            targetPath: "$(Build.ArtifactStagingDirectory)"
            artifactName: "EnterprisePolicies"
            publishLocation: "Container"
        steps:
          - template: .pipelines/templates/BuildCommon.yml@self
            parameters:
              Official: true

      - job: Release
        displayName: "Release"
        dependsOn: Build
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact  # Required, type of the input artifact
            artifactName: "EnterprisePolicies"  # Required, name of the pipeline artifact
            targetPath: $(Pipeline.Workspace)/drop
        steps:
          - task: GithubRelease@1 
            displayName: '🚢 Create GitHub Release'
            inputs:
              gitHubConnection: 'github.com_faix'
              action: 'create'
              repositoryName: microsoft/PowerPlatform-EnterprisePolicies
              target: '$(Build.SourceVersion)'
              tagSource: userSpecifiedTag
              tag: v$(Build.BuildNumber)
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'commitBased'
              assets: |
                  $(Pipeline.Workspace)/drop/EnterprisePolicies_v$(Build.BuildNumber).zip

