name: Azure Pipelines PR Build

trigger: none

pr:
  branches:
    include:
    - main

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: self
    type: githubenterprise
    name: microsoft/PowerPlatform-EnterprisePolicies

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    sdl:
      tsa:
        enabled: false
      binskim:
        enabled: true
      codeql:
        enabled: true
        compiled:
          enabled: false #No compiled languages in this repo
        runSourceLanguagesInSourceAnalysis: true
      credscan:
        enabled: true
        suppressionsFile: $(Build.SourcesDirectory)/.config/CredScanSuppressions.json
      policheck:
        enabled: true
        exclusionFile: $(Build.SourcesDirectory)/.config/PolicyCheckExclusions.json
      psscriptanalyzer:
        break: true
        enabled: true
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-2022
        os: windows

    stages:
    - stage: Build
      jobs:
      - job: Build
        displayName: "Build"
        templateContext:
          outputs:
          - output: pipelineArtifact
            targetPath: "$(Build.ArtifactStagingDirectory)"
            artifactName: "Microsoft.PowerPlatform.EnterprisePolicies"
            publishLocation: "Container"
        steps:
          - template: .pipelines/templates/BuildCommon.yml@self
            parameters:
              Official: false

